# Homework 0

## The Monty Hall Problem


Here's a fun and perhaps surprising statistical riddle, and a good way to get some practice writing python functions

In a gameshow, contestants try to guess which of 3 closed doors contain a cash prize (goats are behind the other two doors). Of course, the odds of choosing the correct door are 1 in 3. As a twist, the host of the show occasionally opens a door after a contestant makes his or her choice. This door is always one of the two the contestant did not pick, and is also always one of the goat doors (note that it is always possible to do this, since there are two goat doors). At this point, the contestant has the option of keeping his or her original choice, or swtiching to the other unopened door. The question is: is there any benefit to switching doors? The answer surprises many people who haven't heard the question before.

We can answer the problem by running simulations in Python. We'll do it in several parts.

First, write a function called `simulate_prizedoor`. This function will simulate the location of the prize in many games -- see the detailed specification below:

In [17]:
"""
Function
--------
simulate_prizedoor

Generate a random array of 0s, 1s, and 2s, representing
hiding a prize between door 0, door 1, and door 2

Parameters
----------
nsim : int
    The number of simulations to run

Returns
-------
sims : array
    Random array of 0s, 1s, and 2s

Example
-------
>>> print simulate_prizedoor(3)
array([0, 0, 2])
"""
"""def simulate_prizedoor(nsim):
    #compute here
    return answer
"""

import numpy as np
import random as rm 

##nsim=20000 ## defines the number of simulations
##ndoor=6

def simulate_prizedoor(nsim):
    ##this step returns random numbers from (0,ndoors) and is listed into a list which nsim long
    ##sims = np.array([rm.randrange(0, ndoors) for _ in range(0, nsim)])
    sims = np.array([rm.randrange(0, 3) for _ in range(0, nsim)])
    return sims

prizedoors = simulate_prizedoor(nsim)
print(prizedoors)

#print(np.shape(simulate_prizedoor(nsim)))



[0 0 2 ..., 0 0 2]


Next, write a function that simulates the contestant's guesses for `nsim` simulations. Call this function `simulate_guess`. The specs:

In [18]:
"""
Function
--------
simulate_guess

Return any strategy for guessing which door a prize is behind. This
could be a random strategy, one that always guesses 2, whatever.

Parameters
----------
nsim : int
    The number of simulations to generate guesses for

Returns
-------
guesses : array
    An array of guesses. Each guess is a 0, 1, or 2

Example
-------
>>> print simulate_guess(5)
array([0, 0, 0, 0, 0])
"""

def simulate_guess(nsim):
    ##this step returns random numbers from (0,ndoors) and is listed into a list which nsim long
    sims = np.array([rm.randrange(0, 3) for _ in range(0, nsim)])
    return sims

guess = simulate_guess(nsim)
print(guess)

[2 1 1 ..., 2 1 1]


Next, write a function, `goat_door`, to simulate randomly revealing one of the goat doors that a contestant didn't pick.

In [19]:
"""
Function
--------
goat_door

Simulate the opening of a "goat door" that doesn't contain the prize,
and is different from the contestants guess

Parameters
----------
prizedoors : array
    The door that the prize is behind in each simulation
guesses : array
    THe door that the contestant guessed in each simulation

Returns
-------
goats : array
    The goat door that is opened for each simulation. Each item is 0, 1, or 2, and is different
    from both prizedoors and guesses

Examples
--------
>>> print goat_door(np.array([0, 1, 2]), np.array([1, 1, 1]))
>>> array([2, 2, 0])
"""
#your code here
print(prizedoors)
print(guess)
def goat_door(prizedoors,guess) :
    prize_guess_combined = np.stack((prizedoors,guess),axis = -1)
    #print(prize_guess_combined[0])
    ##list of all the available doors 
    #avlble_doors = np.array(range(0,ndoor))
    avlble_doors = np.array(range(0,3))
    ##print(avlble_doors)
    #print(list(set(prize_guess_combined[0])))
    op_arr = np.array([],dtype=np.int32)

    for ar in prize_guess_combined : 
        op_arr= np.append(op_arr,(rm.sample(set(avlble_doors[np.in1d(avlble_doors,list(set(ar)),invert=True )]),1)))
    
    return op_arr

goatdoors=goat_door(prizedoors,guess)
print ("goat doors" ) ; print(goatdoors)

[0 0 2 ..., 0 0 2]
[2 1 1 ..., 2 1 1]
goat doors
[1 2 0 ..., 1 2 0]


Write a function, `switch_guess`, that represents the strategy of always switching a guess after the goat door is opened.

In [20]:
"""
Function
--------
switch_guess

The strategy that always switches a guess after the goat door is opened

Parameters
----------
guesses : array
     Array of original guesses, for each simulation
goatdoors : array
     Array of revealed goat doors for each simulation

Returns
-------
The new door after switching. Should be different from both guesses and goatdoors

Examples
--------
>>> print switch_guess(np.array([0, 1, 2]), np.array([1, 2, 1]))
>>> array([2, 0, 0])

"""
#your code here
print("goat doors "); print(goatdoors)
print("guess ");print(guess)

def switch_guess(goatdoors,guess) :
    goatdoors_guess_combined = np.stack((goatdoors,guess),axis = -1)

    #print(goatdoors_guess_combined)
    
    ##list of all the available doors 
    #avlble_doors = np.array(range(0,ndoor))
    avlble_doors = np.array(range(0,3))
    #print(avlble_doors)
    #print(list(set(goatdoors_guess_combined[0])))
    oput_arr = np.array([],dtype=np.int32)

    for comb_arr in goatdoors_guess_combined : 
        oput_arr= np.append(oput_arr,(rm.sample(set(avlble_doors[np.in1d(avlble_doors,list(set(comb_arr)),invert=True )]),1)))
    
    return oput_arr

switchguess=switch_guess(goatdoors,guess)
print("switch guess ")
print(switchguess)
print("prize doors"); print(prizedoors)




goat doors 
[1 2 0 ..., 1 2 0]
guess 
[2 1 1 ..., 2 1 1]
switch guess 
[0 0 2 ..., 0 0 2]
prize doors
[0 0 2 ..., 0 0 2]


Last function: write a `win_percentage` function that takes an array of `guesses` and `prizedoors`, and returns the percent of correct guesses

In [23]:
"""
Function
--------
win_percentage

Calculate the percent of times that a simulation of guesses is correct

Parameters
-----------
guesses : array
    Guesses for each simulation
prizedoors : array
    Location of prize for each simulation

Returns
--------
percentage : number between 0 and 100
    The win percentage

Examples
---------
>>> print win_percentage(np.array([0, 1, 2]), np.array([0, 0, 0]))
33.333
"""
#your code here

#def win_percentage(prizedoors,guess) :
def win_percentage(prizedoors,guess):
    return ((np.sum([prizedoors == guess]))/nsim)*100



33.545


Now, put it together. Simulate 10000 games where contestant keeps his original guess, and 10000 games where the contestant switches his door after a  goat door is revealed. Compute the percentage of time the contestant wins under either strategy. Is one strategy better than the other?

In [42]:

nsim = 10000

#keep guesses
print("Win chances when keeping guess")
print(str(win_percentage(simulate_prizedoor(nsim), simulate_guess(nsim))) +"%")


#switch scenario
switch_prize_door = simulate_prizedoor(nsim)
switch_guess_sim = simulate_guess(nsim)
goatsdoors = goat_door(switch_prize_door, switch_guess_sim)
guess = switch_guess(switch_guess_sim, goatsdoors)
print("Win chances when switching guess")
print(str(win_percentage(switch_prize_door, guess))+"%")

Win chances when keeping guess
33.25%
Win chances when switching guess
66.42%


Many people find this answer counter-intuitive (famously, PhD mathematicians have incorrectly claimed the result must be wrong. Clearly, none of them knew Python). 

One of the best ways to build intuition about why opening a Goat door affects the odds is to re-run the experiment with 100 doors and one prize. If the game show host opens 98 goat doors after you make your initial selection, would you want to keep your first pick or switch? Can you generalize your simulation code to handle the case of `n` doors?